// <auto-generated />
using BookApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookApi.Data.Migrations
{
    [DbContext(typeof(BookContext))]
    partial class BookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("BookApi.Data.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Лев Толстой",
                            Title = "Война и мир"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Фёдор Достоевский",
                            Title = "Преступление и наказание"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Михаил Булгаков",
                            Title = "Мастер и Маргарита"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Михаил Шолохов",
                            Title = "Тихий Дон"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Чарльз Петцольд",
                            Title = "КОД: Тайный язык информатики"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Дэн Браун",
                            Title = "код да Винчи"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Роберт Мартин",
                            Title = "Чистый код"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
